language: python
python:
- 2.7
sudo: false
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- python bootstrap-buildout.py
- bin/buildout -N -t 3
script:
- bin/test
- bin/pybot docs
- bin/code-analysis
cache:
  directories:
  - eggs
notifications:
  flowdock: 827dea8da0905dbc8399d66eb75868df
