language: python
python:
- 2.7
sudo: false
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- make show test
cache:
  directories:
  - eggs
notifications:
  flowdock: 827dea8da0905dbc8399d66eb75868df
env:
  global:
  - ROBOT_BROWSER=phantomjs
  - PYBOT_ARGS="-v BROWSER:phantomjs"
  matrix:
  - BUILDOUT_ARGS="-N -t 3 -c buildout-plone-4.x.cfg"
  - BUILDOUT_ARGS="-N -t 3 -c buildout-plone-5.0.cfg"
  - BUILDOUT_ARGS="-N -t 3 -c buildout-plone-5.1.cfg"
