language: python
python:
- 2.7
sudo: false
install:
- make BUILDOUT_ARGS="-N -t 3" bin/code-analysis bin/test
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- make test
cache:
  directories:
  - eggs
notifications:
  flowdock: 827dea8da0905dbc8399d66eb75868df
